source 'http://rubygems.org'

gem 'rails', '3.0.20'

#-- Special additions-----------------
# PostgreSQL as the database for ActiveRecord
if RUBY_ENGINE == 'jruby' && RUBY_PLATFORM == 'java'
  gem 'activerecord-jdbcpostgresql-adapter', '~> 1.2'
else
  gem 'pg', '~> 0'
end

# Minitest and Growl:
if RUBY_PLATFORM =~ /darwin/i
  gem 'minitest-growl', '~> 0.0.3'
  # minitest-growl has a small issue with minitest 5:
  gem 'minitest', '~> 4.7.4'
else
  gem('minitest', '~> 5') if RUBY_VERSION < '1.9.3'
end

# Gem cant_wait from sources, relative path:
gem 'cant_wait', path: File.expand_path('../../../..', __FILE__)
#-------------------------
