language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode  # JRuby in 1.9 mode (last was 1.7.3)
  - rbx-19mode    # Rubinius in 1.9 mode (last was 2.0.0, weekly build)
before_script:
  # Before, Travis does a bundle install (cant_wait's Gemfile), installing the last version of Rails
  - psql -c "CREATE ROLE tester WITH LOGIN PASSWORD 'secret';" -U postgres
  - psql -c 'CREATE DATABASE test WITH OWNER=tester;' -U postgres
  # And here we remove Rails to allow its coexistence with others
  - gem uninstall rails  # It used to be a singleton...
  - rake test:bundle
script: rake test:run
