# whitelist/blacklist git branches:
branches:
  only:
    - development
  except:
    - master
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode  # JRuby in 1.9 mode (last was 1.7.3)
  - rbx-19mode    # Rubinius in 1.9 mode (last was 2.0.0, weekly build)
before_script:
  - psql -c "CREATE ROLE tester WITH LOGIN PASSWORD 'secret';" -U postgres
  - psql -c 'CREATE DATABASE test WITH OWNER=tester;' -U postgres
script: rake test:all
