source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

#-- Special additions-----------------
# PostgreSQL as the database for ActiveRecord
if RUBY_ENGINE == 'jruby' && RUBY_PLATFORM == 'java'
  gem 'activerecord-jdbc-adapter', '~> 1.2'
  gem 'activerecord-jdbcpostgresql-adapter', '~> 1.2'
  gem 'jdbc-postgres', '~> 9'
else
  gem 'pg', '~> 0'
end

# Minitest and Growl:
if RUBY_PLATFORM =~ /darwin/i
  gem 'minitest-growl', '~> 0.0.3'
  # minitest-growl has a small issue with minitest 5:
  gem 'minitest', '~> 4.7.4'
else
  gem('minitest', '~> 5') if RUBY_VERSION < '1.9.3'
end

# Gem cant_wait from sources, relative path:
gem 'cant_wait', path: File.expand_path('../../../..', __FILE__)
#-------------------------
