source 'https://rubygems.org'

gem 'rails', '3.2.13'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#-- Special additions-----------------
# PostgreSQL as the database for ActiveRecord
if RUBY_ENGINE == 'jruby' && RUBY_PLATFORM == 'java'
  gem 'activerecord-jdbc-adapter', '~> 1.2'
  gem 'activerecord-jdbcpostgresql-adapter', '~> 1.2'
  gem 'jdbc-postgres', '~> 9'
else
  gem 'pg', '~> 0'
end

# Minitest and Growl:
if RUBY_PLATFORM =~ /darwin/i
  gem 'minitest-growl', '~> 0.0.3'
  # minitest-growl has a small issue with minitest 5:
  gem 'minitest', '~> 4.7.4'
else
  gem('minitest', '~> 5') if RUBY_VERSION < '1.9.3'
end

# Gem cant_wait from sources, relative path:
gem 'cant_wait', path: File.expand_path('../../../..', __FILE__)
#-------------------------

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
