source 'http://rubygems.org'

gem 'rails', '3.1.12'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.1.5'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier',     '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end

#-- Special additions-----------------
# PostgreSQL as the database for ActiveRecord
if RUBY_ENGINE == 'jruby' && RUBY_PLATFORM == 'java'
  gem 'activerecord-jdbc-adapter', '~> 1.2'
  gem 'activerecord-jdbcpostgresql-adapter', '~> 1.2'
  gem 'jdbc-postgres', '~> 9'
else
  gem 'pg', '~> 0'
end

# Minitest and Growl:
if RUBY_PLATFORM =~ /darwin/i
  gem 'minitest-growl', '~> 0.0.3'
  # minitest-growl has a small issue with minitest 5:
  gem 'minitest', '~> 4.7.4'
else
  gem('minitest', '~> 5') if RUBY_VERSION < '1.9.3'
end

# Gem cant_wait from sources, relative path:
gem 'cant_wait', path: File.expand_path('../../../..', __FILE__)
#-------------------------
