source 'http://rubygems.org'

gem 'rails', '3.0.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

#-- Special additions-----------------
# PostgreSQL as the database for ActiveRecord
if RUBY_ENGINE == 'jruby' && RUBY_PLATFORM == 'java'
  gem 'activerecord-jdbc-adapter', '~> 1.2'
  gem 'activerecord-jdbcpostgresql-adapter', '~> 1.2'
  gem 'jdbc-postgres', '~> 9'
else
  gem 'pg', '~> 0'
end

# Minitest and Growl:
if RUBY_PLATFORM =~ /darwin/i
  gem 'minitest-growl', '~> 0.0.3'
  # minitest-growl has a small issue with minitest 5:
  gem 'minitest', '~> 4.7.4'
else
  gem('minitest', '~> 5') if RUBY_VERSION < '1.9.3'
end

# Gem cant_wait from sources, relative path:
gem 'cant_wait', path: File.expand_path('../../../..', __FILE__)
#-------------------------

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger (ruby-debug for Ruby 1.8.7+, ruby-debug19 for Ruby 1.9.2+)
# gem 'ruby-debug'
# gem 'ruby-debug19'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
